/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AppSidebar: typeof import('./../components/App/Sidebar.vue')['default']
    AppToolbar: typeof import('./../components/App/Toolbar.vue')['default']
    Button: typeof import('primevue/button')['default']
    CameraCredentials: typeof import('./../components/Camera/Credentials.vue')['default']
    CameraForm: typeof import('./../components/Camera/Form.vue')['default']
    CameraHeader: typeof import('./../components/Camera/Header.vue')['default']
    CameraSettings: typeof import('./../components/Camera/Settings.vue')['default']
    CameraStream: typeof import('./../components/Camera/Stream.vue')['default']
    Column: typeof import('primevue/column')['default']
    DataTable: typeof import('primevue/datatable')['default']
    InputSwitch: typeof import('primevue/inputswitch')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Knob: typeof import('primevue/knob')['default']
    LogHeader: typeof import('./../components/Log/Header.vue')['default']
    Menu: typeof import('primevue/menu')['default']
    PanelMenu: typeof import('primevue/panelmenu')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Tag: typeof import('primevue/tag')['default']
    VideoHeader: typeof import('./../components/Video/Header.vue')['default']
    VideoPlay: typeof import('./../components/Video/Play.vue')['default']
  }
}
